Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -22,11 +22,11 @@ jobs:
     - name: Build
       run: dotnet build --no-restore
     - name: Test
-      run: dotnet test --no-build --verbosity normal
-    # - name: Test Report
-    #   uses: dorny/test-reporter@v1.5.0
-    #   if: success() || failure()    # run this step even if previous step failed
-    #   with:
-    #     name: .NET Tests            # Name of the check run which will be created
-    #     # path: reports/jest-*.xml    # Path to test results
-    #     reporter: dotnet-trx        # Format of test results
+      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
+    - name: Test Report
+      uses: dorny/test-reporter@v1.5.0
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: .NET Tests            # Name of the check run which will be created
+        path: ./**/*.trx            # Path to test results
+        reporter: dotnet-trx        # Format of test results
